/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSearch: typeof import('./src/components/search-input/app-search.vue')['default']
    Input: typeof import('./src/components/ui/input.vue')['default']
    ProductCard: typeof import('./src/components/product-card/product-card.vue')['default']
    SearchInput: typeof import('./src/components/search-input/search-input.vue')['default']
    UiInput: typeof import('./src/components/ui/input/input.vue')['default']
    UiSelect: typeof import('./src/components/ui/select/select.vue')['default']
  }
}
